# .github/workflows/documentation.yml
name: Build documentation 📖

on:
  push:
    branches:
      - main     # Trigger standalone only on pushes to main, ignore tag pushes
  pull_request:
  workflow_dispatch:
  workflow_call:  # Triggered by publish-to-pypi.yml on tag pushes

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install -r requirements/requirements-docs.txt
      - name: Sphinx build
        run: |
          sphinx-build docs docs/_build
      - name: Deploy to GitHub Pages
        # Deploy if on main OR if invoked by publish-to-pypi on a tag
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/
          force_orphan: true
